blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/built-fast/phpstan-sensitive-parameter/discussions
    about: Ask questions and discuss with the community